### ISSUE TITLE
`DateCountdown` uses `getDerivedStateFromProps` but its initial state is undefined.

### ISSUE THREAD

**Issue by Mdellit110** [cengizhanbasak/react-date-countdown-timer#6] opened 2019-12-04 16:17 UTC
I have a few timers working on my site but in the console, I keep getting an error referring to the initial state not being assigned properly? here the error message : 

Warning: `DateCountdown` uses `getDerivedStateFromProps` but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `DateCountdown`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape. `

**Comment by cengizhanbasak** [comment] 2020-02-09 15:32
Hello, thanks for reporting, the issue is fixed now.

**Closed by cengizhanbasak** 2020-02-09 15:32 UTC
