### ISSUE TITLE
Issue with the animation when there is more than 2 counter in 1 page

### ISSUE THREAD

**Issue by Deanx33** [cengizhanbasak/react-date-countdown-timer#5] opened 2019-09-16 14:50 UTC
Hey i have a slider, in every slide i am using the timer. its works fine when there is only one slider, but as soon as i have multiple slides, the animation starting to break.
i think when there is more than 1 instance of the timer, everytime the animation would only apply to fist instance not to others, any help ?

**Comment by Mdellit110** [comment] 2019-12-04 16:10
I had a similar problem and i think it has something to do with your timers/sliders rendering in at different times. my solution was to have the sections wait for them all to be ready to render all at once.not sure if this is the best fix but it works for now.

**Comment by cengizhanbasak** [comment] 2020-02-09 15:33
Hello, thanks for reporting. The issue is fixed now. Let me know if you see any other issues.

**Closed by cengizhanbasak** 2020-02-09 15:33 UTC
